### ISSUE TITLE
Basic charts: Add multiseries support

### ISSUE THREAD

**Issue by 0xNacho** [proteus-h2020/proteus-charts#14]

**Comment by jorgeyp** [comment]
I propose the following data format for the multiseries charts:
```json
{
  "data": {
    "series1": [
      {"x":1, "y":3},
      {"x":2, "y":12},
      {"x":3, "y":21}
    ],
    "series2": [
      {"x":10,"y":15},
      {"x":13,"y":5},
      {"x":12,"y":2}
    ]
  }
}
```

**Comment by 0xNacho** [comment]
Cool! It looks like a simple format and it's ok for me. I think it is not only for multi-serie charts, but also for single-serie ones. Multi or single serie should depend on the number of object properties, right? @jorgeyp

**Comment by 0xNacho** [comment]
After discussing about it, we agree to use an array of arrays as follows:



``` javascript
var data = [
 {
    key: 's1',
    data: [...]
 },
 {
   key: 's2',
   data: [...]
}   
]

```
